import 'model/city_model.dart';
import 'model/governorate_model.dart';

final governorates = [
  GovernorateModel(
    id: 1,
    governorateNameAr: "القاهرة",
    governorateNameEn: "Cairo",
  ),
  GovernorateModel(
    id: 2,
    governorateNameAr: "الجيزة",
    governorateNameEn: "Giza",
  ),
  GovernorateModel(
    id: 3,
    governorateNameAr: "الأسكندرية",
    governorateNameEn: "Alexandria",
  ),
  GovernorateModel(
    id: 4,
    governorateNameAr: "الدقهلية",
    governorateNameEn: "Dakahlia",
  ),
  GovernorateModel(
    id: 5,
    governorateNameAr: "البحر الأحمر",
    governorateNameEn: "Red Sea",
  ),
  GovernorateModel(
    id: 6,
    governorateNameAr: "البحيرة",
    governorateNameEn: "Beheira",
  ),
  GovernorateModel(
    id: 7,
    governorateNameAr: "الفيوم",
    governorateNameEn: "Fayoum",
  ),
  GovernorateModel(
    id: 8,
    governorateNameAr: "الغربية",
    governorateNameEn: "Gharbiya",
  ),
  GovernorateModel(
    id: 9,
    governorateNameAr: "الإسماعلية",
    governorateNameEn: "Ismailia",
  ),
  GovernorateModel(
    id: 10,
    governorateNameAr: "المنوفية",
    governorateNameEn: "Menofia",
  ),
  GovernorateModel(
    id: 11,
    governorateNameAr: "المنيا",
    governorateNameEn: "Minya",
  ),
  GovernorateModel(
    id: 12,
    governorateNameAr: "القليوبية",
    governorateNameEn: "Qaliubiya",
  ),
  GovernorateModel(
    id: 13,
    governorateNameAr: "الوادي الجديد",
    governorateNameEn: "New Valley",
  ),
  GovernorateModel(
    id: 14,
    governorateNameAr: "السويس",
    governorateNameEn: "Suez",
  ),
  GovernorateModel(
    id: 15,
    governorateNameAr: "اسوان",
    governorateNameEn: "Aswan",
  ),
  GovernorateModel(
    id: 16,
    governorateNameAr: "اسيوط",
    governorateNameEn: "Assiut",
  ),
  GovernorateModel(
    id: 17,
    governorateNameAr: "بني سويف",
    governorateNameEn: "Beni Suef",
  ),
  GovernorateModel(
    id: 18,
    governorateNameAr: "بورسعيد",
    governorateNameEn: "Port Said",
  ),
  GovernorateModel(
    id: 19,
    governorateNameAr: "دمياط",
    governorateNameEn: "Damietta",
  ),
  GovernorateModel(
    id: 20,
    governorateNameAr: "الشرقية",
    governorateNameEn: "Sharkia",
  ),
  GovernorateModel(
    id: 21,
    governorateNameAr: "جنوب سيناء",
    governorateNameEn: "South Sinai",
  ),
  GovernorateModel(
    id: 22,
    governorateNameAr: "كفر الشيخ",
    governorateNameEn: "Kafr Al sheikh",
  ),
  GovernorateModel(
    id: 23,
    governorateNameAr: "مطروح",
    governorateNameEn: "Matrouh",
  ),
  GovernorateModel(
    id: 24,
    governorateNameAr: "الأقصر",
    governorateNameEn: "Luxor",
  ),
  GovernorateModel(
    id: 25,
    governorateNameAr: "قنا",
    governorateNameEn: "Qena",
  ),
  GovernorateModel(
    id: 26,
    governorateNameAr: "شمال سيناء",
    governorateNameEn: "North Sinai",
  ),
  GovernorateModel(
    id: 27,
    governorateNameAr: "سوهاج",
    governorateNameEn: "Sohag",
  ),
];
final cities = [
  CityModel(
    id: 1,
    governorateId: 1,
    cityNameAr: "15 مايو",
    cityNameEn: "15 May",
  ),
  CityModel(
    id: 2,
    governorateId: 1,
    cityNameAr: "الازبكية",
    cityNameEn: "Al Azbakeyah",
  ),
  CityModel(
    id: 3,
    governorateId: 1,
    cityNameAr: "البساتين",
    cityNameEn: "Al Basatin",
  ),
  CityModel(
    id: 4,
    governorateId: 1,
    cityNameAr: "التبين",
    cityNameEn: "Tebin",
  ),
  CityModel(
    id: 5,
    governorateId: 1,
    cityNameAr: "الخليفة",
    cityNameEn: "El-Khalifa",
  ),
  CityModel(
    id: 6,
    governorateId: 1,
    cityNameAr: "الدراسة",
    cityNameEn: "El darrasa",
  ),
  CityModel(
    id: 7,
    governorateId: 1,
    cityNameAr: "الدرب الاحمر",
    cityNameEn: "Aldarb Alahmar",
  ),
  CityModel(
    id: 8,
    governorateId: 1,
    cityNameAr: "الزاوية الحمراء",
    cityNameEn: "Zawya al-Hamra",
  ),
  CityModel(
    id: 9,
    governorateId: 1,
    cityNameAr: "الزيتون",
    cityNameEn: "El-Zaytoun",
  ),
  CityModel(
    id: 10,
    governorateId: 1,
    cityNameAr: "الساحل",
    cityNameEn: "Sahel",
  ),
  CityModel(
    id: 11,
    governorateId: 1,
    cityNameAr: "السلام",
    cityNameEn: "El Salam",
  ),
  CityModel(
    id: 12,
    governorateId: 1,
    cityNameAr: "السيدة زينب",
    cityNameEn: "Sayeda Zeinab",
  ),
  CityModel(
    id: 13,
    governorateId: 1,
    cityNameAr: "الشرابية",
    cityNameEn: "El Sharabeya",
  ),
  CityModel(
    id: 14,
    governorateId: 1,
    cityNameAr: "مدينة الشروق",
    cityNameEn: "Shorouk",
  ),
  CityModel(
    id: 15,
    governorateId: 1,
    cityNameAr: "الظاهر",
    cityNameEn: "El Daher",
  ),
  CityModel(
    id: 16,
    governorateId: 1,
    cityNameAr: "العتبة",
    cityNameEn: "Ataba",
  ),
  CityModel(
    id: 17,
    governorateId: 1,
    cityNameAr: "القاهرة الجديدة",
    cityNameEn: "New Cairo",
  ),
  CityModel(
    id: 18,
    governorateId: 1,
    cityNameAr: "المرج",
    cityNameEn: "El Marg",
  ),
  CityModel(
    id: 19,
    governorateId: 1,
    cityNameAr: "عزبة النخل",
    cityNameEn: "Ezbet el Nakhl",
  ),
  CityModel(
    id: 20,
    governorateId: 1,
    cityNameAr: "المطرية",
    cityNameEn: "Matareya",
  ),
  CityModel(
    id: 21,
    governorateId: 1,
    cityNameAr: "المعادى",
    cityNameEn: "Maadi",
  ),
  CityModel(
    id: 22,
    governorateId: 1,
    cityNameAr: "المعصرة",
    cityNameEn: "Maasara",
  ),
  CityModel(
    id: 23,
    governorateId: 1,
    cityNameAr: "المقطم",
    cityNameEn: "Mokattam",
  ),
  CityModel(
    id: 24,
    governorateId: 1,
    cityNameAr: "المنيل",
    cityNameEn: "Manyal",
  ),
  CityModel(
    id: 25,
    governorateId: 1,
    cityNameAr: "الموسكى",
    cityNameEn: "Mosky",
  ),
  CityModel(
    id: 26,
    governorateId: 1,
    cityNameAr: "النزهة",
    cityNameEn: "Nozha",
  ),
  CityModel(
    id: 27,
    governorateId: 1,
    cityNameAr: "الوايلى",
    cityNameEn: "Waily",
  ),
  CityModel(
    id: 28,
    governorateId: 1,
    cityNameAr: "باب الشعرية",
    cityNameEn: "Bab al-Shereia",
  ),
  CityModel(
    id: 29,
    governorateId: 1,
    cityNameAr: "بولاق",
    cityNameEn: "Bolaq",
  ),
  CityModel(
    id: 30,
    governorateId: 1,
    cityNameAr: "جاردن سيتى",
    cityNameEn: "Garden City",
  ),
  CityModel(
    id: 31,
    governorateId: 1,
    cityNameAr: "حدائق القبة",
    cityNameEn: "Hadayek El-Kobba",
  ),
  CityModel(
    id: 32,
    governorateId: 1,
    cityNameAr: "حلوان",
    cityNameEn: "Helwan",
  ),
  CityModel(
    id: 33,
    governorateId: 1,
    cityNameAr: "دار السلام",
    cityNameEn: "Dar Al Salam",
  ),
  CityModel(
    id: 34,
    governorateId: 1,
    cityNameAr: "شبرا",
    cityNameEn: "Shubra",
  ),
  CityModel(
    id: 35,
    governorateId: 1,
    cityNameAr: "طره",
    cityNameEn: "Tura",
  ),
  CityModel(
    id: 36,
    governorateId: 1,
    cityNameAr: "عابدين",
    cityNameEn: "Abdeen",
  ),
  CityModel(
    id: 37,
    governorateId: 1,
    cityNameAr: "عباسية",
    cityNameEn: "Abaseya",
  ),
  CityModel(
    id: 38,
    governorateId: 1,
    cityNameAr: "عين شمس",
    cityNameEn: "Ain Shams",
  ),
  CityModel(
    id: 39,
    governorateId: 1,
    cityNameAr: "مدينة نصر",
    cityNameEn: "Nasr City",
  ),
  CityModel(
    id: 40,
    governorateId: 1,
    cityNameAr: "مصر الجديدة",
    cityNameEn: "New Heliopolis",
  ),
  CityModel(
    id: 41,
    governorateId: 1,
    cityNameAr: "مصر القديمة",
    cityNameEn: "Masr Al Qadima",
  ),
  CityModel(
    id: 42,
    governorateId: 1,
    cityNameAr: "منشية ناصر",
    cityNameEn: "Mansheya Nasir",
  ),
  CityModel(
    id: 43,
    governorateId: 1,
    cityNameAr: "مدينة بدر",
    cityNameEn: "Badr City",
  ),
  CityModel(
    id: 44,
    governorateId: 1,
    cityNameAr: "مدينة العبور",
    cityNameEn: "Obour City",
  ),
  CityModel(
    id: 45,
    governorateId: 1,
    cityNameAr: "وسط البلد",
    cityNameEn: "Cairo Downtown",
  ),
  CityModel(
    id: 46,
    governorateId: 1,
    cityNameAr: "الزمالك",
    cityNameEn: "Zamalek",
  ),
  CityModel(
    id: 47,
    governorateId: 1,
    cityNameAr: "قصر النيل",
    cityNameEn: "Kasr El Nile",
  ),
  CityModel(
    id: 48,
    governorateId: 1,
    cityNameAr: "الرحاب",
    cityNameEn: "Rehab",
  ),
  CityModel(
    id: 49,
    governorateId: 1,
    cityNameAr: "القطامية",
    cityNameEn: "Katameya",
  ),
  CityModel(
    id: 50,
    governorateId: 1,
    cityNameAr: "مدينتي",
    cityNameEn: "Madinty",
  ),
  CityModel(
    id: 51,
    governorateId: 1,
    cityNameAr: "روض الفرج",
    cityNameEn: "Rod Alfarag",
  ),
  CityModel(
    id: 52,
    governorateId: 1,
    cityNameAr: "شيراتون",
    cityNameEn: "Sheraton",
  ),
  CityModel(
    id: 53,
    governorateId: 1,
    cityNameAr: "الجمالية",
    cityNameEn: "El-Gamaleya",
  ),
  CityModel(
    id: 54,
    governorateId: 1,
    cityNameAr: "العاشر من رمضان",
    cityNameEn: "10th of Ramadan City",
  ),
  CityModel(
    id: 55,
    governorateId: 1,
    cityNameAr: "الحلمية",
    cityNameEn: "Helmeyat Alzaytoun",
  ),
  CityModel(
    id: 56,
    governorateId: 1,
    cityNameAr: "النزهة الجديدة",
    cityNameEn: "New Nozha",
  ),
  CityModel(
    id: 57,
    governorateId: 1,
    cityNameAr: "العاصمة الإدارية",
    cityNameEn: "Capital New",
  ),
  CityModel(
    id: 58,
    governorateId: 2,
    cityNameAr: "الجيزة",
    cityNameEn: "Giza",
  ),
  CityModel(
    id: 59,
    governorateId: 2,
    cityNameAr: "السادس من أكتوبر",
    cityNameEn: "Sixth of October",
  ),
  CityModel(
    id: 60,
    governorateId: 2,
    cityNameAr: "الشيخ زايد",
    cityNameEn: "Cheikh Zayed",
  ),
  CityModel(
    id: 61,
    governorateId: 2,
    cityNameAr: "الحوامدية",
    cityNameEn: "Hawamdiyah",
  ),
  CityModel(
    id: 62,
    governorateId: 2,
    cityNameAr: "البدرشين",
    cityNameEn: "Al Badrasheen",
  ),
  CityModel(
    id: 63,
    governorateId: 2,
    cityNameAr: "الصف",
    cityNameEn: "Saf",
  ),
  CityModel(
    id: 64,
    governorateId: 2,
    cityNameAr: "أطفيح",
    cityNameEn: "Atfih",
  ),
  CityModel(
    id: 65,
    governorateId: 2,
    cityNameAr: "العياط",
    cityNameEn: "Al Ayat",
  ),
  CityModel(
    id: 66,
    governorateId: 2,
    cityNameAr: "الباويطي",
    cityNameEn: "Al-Bawaiti",
  ),
  CityModel(
    id: 67,
    governorateId: 2,
    cityNameAr: "منشأة القناطر",
    cityNameEn: "ManshiyetAl Qanater",
  ),
  CityModel(
    id: 68,
    governorateId: 2,
    cityNameAr: "أوسيم",
    cityNameEn: "Oaseem",
  ),
  CityModel(
    id: 69,
    governorateId: 2,
    cityNameAr: "كرداسة",
    cityNameEn: "Kerdasa",
  ),
  CityModel(
    id: 70,
    governorateId: 2,
    cityNameAr: "أبو النمرس",
    cityNameEn: "Abu Nomros",
  ),
  CityModel(
    id: 71,
    governorateId: 2,
    cityNameAr: "كفر غطاطي",
    cityNameEn: "Kafr Ghati",
  ),
  CityModel(
    id: 72,
    governorateId: 2,
    cityNameAr: "منشأة البكاري",
    cityNameEn: "Manshiyet Al Bakari",
  ),
  CityModel(
    id: 73,
    governorateId: 2,
    cityNameAr: "الدقى",
    cityNameEn: "Dokki",
  ),
  CityModel(
    id: 74,
    governorateId: 2,
    cityNameAr: "العجوزة",
    cityNameEn: "Agouza",
  ),
  CityModel(
    id: 75,
    governorateId: 2,
    cityNameAr: "الهرم",
    cityNameEn: "Haram",
  ),
  CityModel(
    id: 76,
    governorateId: 2,
    cityNameAr: "الوراق",
    cityNameEn: "Warraq",
  ),
  CityModel(
    id: 77,
    governorateId: 2,
    cityNameAr: "امبابة",
    cityNameEn: "Imbaba",
  ),
  CityModel(
    id: 78,
    governorateId: 2,
    cityNameAr: "بولاق الدكرور",
    cityNameEn: "Boulaq Dakrour",
  ),
  CityModel(
    id: 79,
    governorateId: 2,
    cityNameAr: "الواحات البحرية",
    cityNameEn: "Al Wahat Al Baharia",
  ),
  CityModel(
    id: 80,
    governorateId: 2,
    cityNameAr: "العمرانية",
    cityNameEn: "Omraneya",
  ),
  CityModel(
    id: 81,
    governorateId: 2,
    cityNameAr: "المنيب",
    cityNameEn: "Moneeb",
  ),
  CityModel(
    id: 82,
    governorateId: 2,
    cityNameAr: "بين السرايات",
    cityNameEn: "Bin Alsarayat",
  ),
  CityModel(
    id: 83,
    governorateId: 2,
    cityNameAr: "الكيت كات",
    cityNameEn: "Kit Kat",
  ),
  CityModel(
    id: 84,
    governorateId: 2,
    cityNameAr: "المهندسين",
    cityNameEn: "Mohandessin",
  ),
  CityModel(
    id: 85,
    governorateId: 2,
    cityNameAr: "فيصل",
    cityNameEn: "Faisal",
  ),
  CityModel(
    id: 86,
    governorateId: 2,
    cityNameAr: "أبو رواش",
    cityNameEn: "Abu Rawash",
  ),
  CityModel(
    id: 87,
    governorateId: 2,
    cityNameAr: "حدائق الأهرام",
    cityNameEn: "Hadayek Alahram",
  ),
  CityModel(
    id: 88,
    governorateId: 2,
    cityNameAr: "الحرانية",
    cityNameEn: "Haraneya",
  ),
  CityModel(
    id: 89,
    governorateId: 2,
    cityNameAr: "حدائق اكتوبر",
    cityNameEn: "Hadayek October",
  ),
  CityModel(
    id: 90,
    governorateId: 2,
    cityNameAr: "صفط اللبن",
    cityNameEn: "Saft Allaban",
  ),
  CityModel(
    id: 91,
    governorateId: 2,
    cityNameAr: "القرية الذكية",
    cityNameEn: "Smart Village",
  ),
  CityModel(
    id: 92,
    governorateId: 2,
    cityNameAr: "ارض اللواء",
    cityNameEn: "Ard Ellwaa",
  ),
  CityModel(
    id: 93,
    governorateId: 3,
    cityNameAr: "ابو قير",
    cityNameEn: "Abu Qir",
  ),
  CityModel(
    id: 94,
    governorateId: 3,
    cityNameAr: "الابراهيمية",
    cityNameEn: "Al Ibrahimeyah",
  ),
  CityModel(
    id: 95,
    governorateId: 3,
    cityNameAr: "الأزاريطة",
    cityNameEn: "Azarita",
  ),
  CityModel(
    id: 96,
    governorateId: 3,
    cityNameAr: "الانفوشى",
    cityNameEn: "Anfoushi",
  ),
  CityModel(
    id: 97,
    governorateId: 3,
    cityNameAr: "الدخيلة",
    cityNameEn: "Dekheila",
  ),
  CityModel(
    id: 98,
    governorateId: 3,
    cityNameAr: "السيوف",
    cityNameEn: "El Soyof",
  ),
  CityModel(
    id: 99,
    governorateId: 3,
    cityNameAr: "العامرية",
    cityNameEn: "Ameria",
  ),
  CityModel(
    id: 100,
    governorateId: 3,
    cityNameAr: "اللبان",
    cityNameEn: "El Labban",
  ),
  CityModel(
    id: 101,
    governorateId: 3,
    cityNameAr: "المفروزة",
    cityNameEn: "Al Mafrouza",
  ),
  CityModel(
    id: 102,
    governorateId: 3,
    cityNameAr: "المنتزه",
    cityNameEn: "El Montaza",
  ),
  CityModel(
    id: 103,
    governorateId: 3,
    cityNameAr: "المنشية",
    cityNameEn: "Mansheya",
  ),
  CityModel(
    id: 104,
    governorateId: 3,
    cityNameAr: "الناصرية",
    cityNameEn: "Naseria",
  ),
  CityModel(
    id: 105,
    governorateId: 3,
    cityNameAr: "امبروزو",
    cityNameEn: "Ambrozo",
  ),
  CityModel(
    id: 106,
    governorateId: 3,
    cityNameAr: "باب شرق",
    cityNameEn: "Bab Sharq",
  ),
  CityModel(
    id: 107,
    governorateId: 3,
    cityNameAr: "برج العرب",
    cityNameEn: "Bourj Alarab",
  ),
  CityModel(
    id: 108,
    governorateId: 3,
    cityNameAr: "ستانلى",
    cityNameEn: "Stanley",
  ),
  CityModel(
    id: 109,
    governorateId: 3,
    cityNameAr: "سموحة",
    cityNameEn: "Smouha",
  ),
  CityModel(
    id: 110,
    governorateId: 3,
    cityNameAr: "سيدى بشر",
    cityNameEn: "Sidi Bishr",
  ),
  CityModel(
    id: 111,
    governorateId: 3,
    cityNameAr: "شدس",
    cityNameEn: "Shads",
  ),
  CityModel(
    id: 112,
    governorateId: 3,
    cityNameAr: "غيط العنب",
    cityNameEn: "Gheet Alenab",
  ),
  CityModel(
    id: 113,
    governorateId: 3,
    cityNameAr: "فلمينج",
    cityNameEn: "Fleming",
  ),
  CityModel(
    id: 114,
    governorateId: 3,
    cityNameAr: "فيكتوريا",
    cityNameEn: "Victoria",
  ),
  CityModel(
    id: 115,
    governorateId: 3,
    cityNameAr: "كامب شيزار",
    cityNameEn: "Camp Shizar",
  ),
  CityModel(
    id: 116,
    governorateId: 3,
    cityNameAr: "كرموز",
    cityNameEn: "Karmooz",
  ),
  CityModel(
    id: 117,
    governorateId: 3,
    cityNameAr: "محطة الرمل",
    cityNameEn: "Mahta Alraml",
  ),
  CityModel(
    id: 118,
    governorateId: 3,
    cityNameAr: "مينا البصل",
    cityNameEn: "Mina El-Basal",
  ),
  CityModel(
    id: 119,
    governorateId: 3,
    cityNameAr: "العصافرة",
    cityNameEn: "Asafra",
  ),
  CityModel(
    id: 120,
    governorateId: 3,
    cityNameAr: "العجمي",
    cityNameEn: "Agamy",
  ),
  CityModel(
    id: 121,
    governorateId: 3,
    cityNameAr: "بكوس",
    cityNameEn: "Bakos",
  ),
  CityModel(
    id: 122,
    governorateId: 3,
    cityNameAr: "بولكلي",
    cityNameEn: "Boulkly",
  ),
  CityModel(
    id: 123,
    governorateId: 3,
    cityNameAr: "كليوباترا",
    cityNameEn: "Cleopatra",
  ),
  CityModel(
    id: 124,
    governorateId: 3,
    cityNameAr: "جليم",
    cityNameEn: "Glim",
  ),
  CityModel(
    id: 125,
    governorateId: 3,
    cityNameAr: "المعمورة",
    cityNameEn: "Al Mamurah",
  ),
  CityModel(
    id: 126,
    governorateId: 3,
    cityNameAr: "المندرة",
    cityNameEn: "Al Mandara",
  ),
  CityModel(
    id: 127,
    governorateId: 3,
    cityNameAr: "محرم بك",
    cityNameEn: "Moharam Bek",
  ),
  CityModel(
    id: 128,
    governorateId: 3,
    cityNameAr: "الشاطبي",
    cityNameEn: "Elshatby",
  ),
  CityModel(
    id: 129,
    governorateId: 3,
    cityNameAr: "سيدي جابر",
    cityNameEn: "Sidi Gaber",
  ),
  CityModel(
    id: 130,
    governorateId: 3,
    cityNameAr: "الساحل الشمالي",
    cityNameEn: "North Coast\/sahel",
  ),
  CityModel(
    id: 131,
    governorateId: 3,
    cityNameAr: "الحضرة",
    cityNameEn: "Alhadra",
  ),
  CityModel(
    id: 132,
    governorateId: 3,
    cityNameAr: "العطارين",
    cityNameEn: "Alattarin",
  ),
  CityModel(
    id: 133,
    governorateId: 3,
    cityNameAr: "سيدي كرير",
    cityNameEn: "Sidi Kerir",
  ),
  CityModel(
    id: 134,
    governorateId: 3,
    cityNameAr: "الجمرك",
    cityNameEn: "Elgomrok",
  ),
  CityModel(
    id: 135,
    governorateId: 3,
    cityNameAr: "المكس",
    cityNameEn: "Al Max",
  ),
  CityModel(
    id: 136,
    governorateId: 3,
    cityNameAr: "مارينا",
    cityNameEn: "Marina",
  ),
  CityModel(
    id: 137,
    governorateId: 4,
    cityNameAr: "المنصورة",
    cityNameEn: "Mansoura",
  ),
  CityModel(
    id: 138,
    governorateId: 4,
    cityNameAr: "طلخا",
    cityNameEn: "Talkha",
  ),
  CityModel(
    id: 139,
    governorateId: 4,
    cityNameAr: "ميت غمر",
    cityNameEn: "Mitt Ghamr",
  ),
  CityModel(
    id: 140,
    governorateId: 4,
    cityNameAr: "دكرنس",
    cityNameEn: "Dekernes",
  ),
  CityModel(
    id: 141,
    governorateId: 4,
    cityNameAr: "أجا",
    cityNameEn: "Aga",
  ),
  CityModel(
    id: 142,
    governorateId: 4,
    cityNameAr: "منية النصر",
    cityNameEn: "Menia El Nasr",
  ),
  CityModel(
    id: 143,
    governorateId: 4,
    cityNameAr: "السنبلاوين",
    cityNameEn: "Sinbillawin",
  ),
  CityModel(
    id: 144,
    governorateId: 4,
    cityNameAr: "الكردي",
    cityNameEn: "El Kurdi",
  ),
  CityModel(
    id: 145,
    governorateId: 4,
    cityNameAr: "بني عبيد",
    cityNameEn: "Bani Ubaid",
  ),
  CityModel(
    id: 146,
    governorateId: 4,
    cityNameAr: "المنزلة",
    cityNameEn: "Al Manzala",
  ),
  CityModel(
    id: 147,
    governorateId: 4,
    cityNameAr: "تمي الأمديد",
    cityNameEn: "tami al'amdid",
  ),
  CityModel(
    id: 148,
    governorateId: 4,
    cityNameAr: "الجمالية",
    cityNameEn: "aljamalia",
  ),
  CityModel(
    id: 149,
    governorateId: 4,
    cityNameAr: "شربين",
    cityNameEn: "Sherbin",
  ),
  CityModel(
    id: 150,
    governorateId: 4,
    cityNameAr: "المطرية",
    cityNameEn: "Mataria",
  ),
  CityModel(
    id: 151,
    governorateId: 4,
    cityNameAr: "بلقاس",
    cityNameEn: "Belqas",
  ),
  CityModel(
    id: 152,
    governorateId: 4,
    cityNameAr: "ميت سلسيل",
    cityNameEn: "Meet Salsil",
  ),
  CityModel(
    id: 153,
    governorateId: 4,
    cityNameAr: "جمصة",
    cityNameEn: "Gamasa",
  ),
  CityModel(
    id: 154,
    governorateId: 4,
    cityNameAr: "محلة دمنة",
    cityNameEn: "Mahalat Damana",
  ),
  CityModel(
    id: 155,
    governorateId: 4,
    cityNameAr: "نبروه",
    cityNameEn: "Nabroh",
  ),
  CityModel(
    id: 156,
    governorateId: 5,
    cityNameAr: "الغردقة",
    cityNameEn: "Hurghada",
  ),
  CityModel(
    id: 157,
    governorateId: 5,
    cityNameAr: "رأس غارب",
    cityNameEn: "Ras Ghareb",
  ),
  CityModel(
    id: 158,
    governorateId: 5,
    cityNameAr: "سفاجا",
    cityNameEn: "Safaga",
  ),
  CityModel(
    id: 159,
    governorateId: 5,
    cityNameAr: "القصير",
    cityNameEn: "El Qusiar",
  ),
  CityModel(
    id: 160,
    governorateId: 5,
    cityNameAr: "مرسى علم",
    cityNameEn: "Marsa Alam",
  ),
  CityModel(
    id: 161,
    governorateId: 5,
    cityNameAr: "الشلاتين",
    cityNameEn: "Shalatin",
  ),
  CityModel(
    id: 162,
    governorateId: 5,
    cityNameAr: "حلايب",
    cityNameEn: "Halaib",
  ),
  CityModel(
    id: 163,
    governorateId: 5,
    cityNameAr: "الدهار",
    cityNameEn: "Aldahar",
  ),
  CityModel(
    id: 164,
    governorateId: 6,
    cityNameAr: "دمنهور",
    cityNameEn: "Damanhour",
  ),
  CityModel(
    id: 165,
    governorateId: 6,
    cityNameAr: "كفر الدوار",
    cityNameEn: "Kafr El Dawar",
  ),
  CityModel(
    id: 166,
    governorateId: 6,
    cityNameAr: "رشيد",
    cityNameEn: "Rashid",
  ),
  CityModel(
    id: 167,
    governorateId: 6,
    cityNameAr: "إدكو",
    cityNameEn: "Edco",
  ),
  CityModel(
    id: 168,
    governorateId: 6,
    cityNameAr: "أبو المطامير",
    cityNameEn: "Abu al-Matamir",
  ),
  CityModel(
    id: 169,
    governorateId: 6,
    cityNameAr: "أبو حمص",
    cityNameEn: "Abu Homs",
  ),
  CityModel(
    id: 170,
    governorateId: 6,
    cityNameAr: "الدلنجات",
    cityNameEn: "Delengat",
  ),
  CityModel(
    id: 171,
    governorateId: 6,
    cityNameAr: "المحمودية",
    cityNameEn: "Mahmoudiyah",
  ),
  CityModel(
    id: 172,
    governorateId: 6,
    cityNameAr: "الرحمانية",
    cityNameEn: "Rahmaniyah",
  ),
  CityModel(
    id: 173,
    governorateId: 6,
    cityNameAr: "إيتاي البارود",
    cityNameEn: "Itai Baroud",
  ),
  CityModel(
    id: 174,
    governorateId: 6,
    cityNameAr: "حوش عيسى",
    cityNameEn: "Housh Eissa",
  ),
  CityModel(
    id: 175,
    governorateId: 6,
    cityNameAr: "شبراخيت",
    cityNameEn: "Shubrakhit",
  ),
  CityModel(
    id: 176,
    governorateId: 6,
    cityNameAr: "كوم حمادة",
    cityNameEn: "Kom Hamada",
  ),
  CityModel(
    id: 177,
    governorateId: 6,
    cityNameAr: "بدر",
    cityNameEn: "Badr",
  ),
  CityModel(
    id: 178,
    governorateId: 6,
    cityNameAr: "وادي النطرون",
    cityNameEn: "Wadi Natrun",
  ),
  CityModel(
    id: 179,
    governorateId: 6,
    cityNameAr: "النوبارية الجديدة",
    cityNameEn: "New Nubaria",
  ),
  CityModel(
    id: 180,
    governorateId: 6,
    cityNameAr: "النوبارية",
    cityNameEn: "Alnoubareya",
  ),
  CityModel(
    id: 181,
    governorateId: 7,
    cityNameAr: "الفيوم",
    cityNameEn: "Fayoum",
  ),
  CityModel(
    id: 182,
    governorateId: 7,
    cityNameAr: "الفيوم الجديدة",
    cityNameEn: "Fayoum El Gedida",
  ),
  CityModel(
    id: 183,
    governorateId: 7,
    cityNameAr: "طامية",
    cityNameEn: "Tamiya",
  ),
  CityModel(
    id: 184,
    governorateId: 7,
    cityNameAr: "سنورس",
    cityNameEn: "Snores",
  ),
  CityModel(
    id: 185,
    governorateId: 7,
    cityNameAr: "إطسا",
    cityNameEn: "Etsa",
  ),
  CityModel(
    id: 186,
    governorateId: 7,
    cityNameAr: "إبشواي",
    cityNameEn: "Epschway",
  ),
  CityModel(
    id: 187,
    governorateId: 7,
    cityNameAr: "يوسف الصديق",
    cityNameEn: "Yusuf El Sediaq",
  ),
  CityModel(
    id: 188,
    governorateId: 7,
    cityNameAr: "الحادقة",
    cityNameEn: "Hadqa",
  ),
  CityModel(
    id: 189,
    governorateId: 7,
    cityNameAr: "اطسا",
    cityNameEn: "Atsa",
  ),
  CityModel(
    id: 190,
    governorateId: 7,
    cityNameAr: "الجامعة",
    cityNameEn: "Algamaa",
  ),
  CityModel(
    id: 191,
    governorateId: 7,
    cityNameAr: "السيالة",
    cityNameEn: "Sayala",
  ),
  CityModel(
    id: 192,
    governorateId: 8,
    cityNameAr: "طنطا",
    cityNameEn: "Tanta",
  ),
  CityModel(
    id: 193,
    governorateId: 8,
    cityNameAr: "المحلة الكبرى",
    cityNameEn: "Al Mahalla Al Kobra",
  ),
  CityModel(
    id: 194,
    governorateId: 8,
    cityNameAr: "كفر الزيات",
    cityNameEn: "Kafr El Zayat",
  ),
  CityModel(
    id: 195,
    governorateId: 8,
    cityNameAr: "زفتى",
    cityNameEn: "Zefta",
  ),
  CityModel(
    id: 196,
    governorateId: 8,
    cityNameAr: "السنطة",
    cityNameEn: "El Santa",
  ),
  CityModel(
    id: 197,
    governorateId: 8,
    cityNameAr: "قطور",
    cityNameEn: "Qutour",
  ),
  CityModel(
    id: 198,
    governorateId: 8,
    cityNameAr: "بسيون",
    cityNameEn: "Basion",
  ),
  CityModel(
    id: 199,
    governorateId: 8,
    cityNameAr: "سمنود",
    cityNameEn: "Samannoud",
  ),
  CityModel(
    id: 200,
    governorateId: 9,
    cityNameAr: "الإسماعيلية",
    cityNameEn: "Ismailia",
  ),
  CityModel(
    id: 201,
    governorateId: 9,
    cityNameAr: "فايد",
    cityNameEn: "Fayed",
  ),
  CityModel(
    id: 202,
    governorateId: 9,
    cityNameAr: "القنطرة شرق",
    cityNameEn: "Qantara Sharq",
  ),
  CityModel(
    id: 203,
    governorateId: 9,
    cityNameAr: "القنطرة غرب",
    cityNameEn: "Qantara Gharb",
  ),
  CityModel(
    id: 204,
    governorateId: 9,
    cityNameAr: "التل الكبير",
    cityNameEn: "El Tal El Kabier",
  ),
  CityModel(
    id: 205,
    governorateId: 9,
    cityNameAr: "أبو صوير",
    cityNameEn: "Abu Sawir",
  ),
  CityModel(
    id: 206,
    governorateId: 9,
    cityNameAr: "القصاصين الجديدة",
    cityNameEn: "Kasasien El Gedida",
  ),
  CityModel(
    id: 207,
    governorateId: 9,
    cityNameAr: "نفيشة",
    cityNameEn: "Nefesha",
  ),
  CityModel(
    id: 208,
    governorateId: 9,
    cityNameAr: "الشيخ زايد",
    cityNameEn: "Sheikh Zayed",
  ),
  CityModel(
    id: 209,
    governorateId: 10,
    cityNameAr: "شبين الكوم",
    cityNameEn: "Shbeen El Koom",
  ),
  CityModel(
    id: 210,
    governorateId: 10,
    cityNameAr: "مدينة السادات",
    cityNameEn: "Sadat City",
  ),
  CityModel(
    id: 211,
    governorateId: 10,
    cityNameAr: "منوف",
    cityNameEn: "Menouf",
  ),
  CityModel(
    id: 212,
    governorateId: 10,
    cityNameAr: "سرس الليان",
    cityNameEn: "Sars El-Layan",
  ),
  CityModel(
    id: 213,
    governorateId: 10,
    cityNameAr: "أشمون",
    cityNameEn: "Ashmon",
  ),
  CityModel(
    id: 214,
    governorateId: 10,
    cityNameAr: "الباجور",
    cityNameEn: "Al Bagor",
  ),
  CityModel(
    id: 215,
    governorateId: 10,
    cityNameAr: "قويسنا",
    cityNameEn: "Quesna",
  ),
  CityModel(
    id: 216,
    governorateId: 10,
    cityNameAr: "بركة السبع",
    cityNameEn: "Berkat El Saba",
  ),
  CityModel(
    id: 217,
    governorateId: 10,
    cityNameAr: "تلا",
    cityNameEn: "Tala",
  ),
  CityModel(
    id: 218,
    governorateId: 10,
    cityNameAr: "الشهداء",
    cityNameEn: "Al Shohada",
  ),
  CityModel(
    id: 219,
    governorateId: 11,
    cityNameAr: "المنيا",
    cityNameEn: "Minya",
  ),
  CityModel(
    id: 220,
    governorateId: 11,
    cityNameAr: "المنيا الجديدة",
    cityNameEn: "Minya El Gedida",
  ),
  CityModel(
    id: 221,
    governorateId: 11,
    cityNameAr: "العدوة",
    cityNameEn: "El Adwa",
  ),
  CityModel(
    id: 222,
    governorateId: 11,
    cityNameAr: "مغاغة",
    cityNameEn: "Magagha",
  ),
  CityModel(
    id: 223,
    governorateId: 11,
    cityNameAr: "بني مزار",
    cityNameEn: "Bani Mazar",
  ),
  CityModel(
    id: 224,
    governorateId: 11,
    cityNameAr: "مطاي",
    cityNameEn: "Mattay",
  ),
  CityModel(
    id: 225,
    governorateId: 11,
    cityNameAr: "سمالوط",
    cityNameEn: "Samalut",
  ),
  CityModel(
    id: 226,
    governorateId: 11,
    cityNameAr: "المدينة الفكرية",
    cityNameEn: "Madinat El Fekria",
  ),
  CityModel(
    id: 227,
    governorateId: 11,
    cityNameAr: "ملوي",
    cityNameEn: "Meloy",
  ),
  CityModel(
    id: 228,
    governorateId: 11,
    cityNameAr: "دير مواس",
    cityNameEn: "Deir Mawas",
  ),
  CityModel(
    id: 229,
    governorateId: 11,
    cityNameAr: "ابو قرقاص",
    cityNameEn: "Abu Qurqas",
  ),
  CityModel(
    id: 230,
    governorateId: 11,
    cityNameAr: "ارض سلطان",
    cityNameEn: "Ard Sultan",
  ),
  CityModel(
    id: 231,
    governorateId: 12,
    cityNameAr: "بنها",
    cityNameEn: "Banha",
  ),
  CityModel(
    id: 232,
    governorateId: 12,
    cityNameAr: "قليوب",
    cityNameEn: "Qalyub",
  ),
  CityModel(
    id: 233,
    governorateId: 12,
    cityNameAr: "شبرا الخيمة",
    cityNameEn: "Shubra Al Khaimah",
  ),
  CityModel(
    id: 234,
    governorateId: 12,
    cityNameAr: "القناطر الخيرية",
    cityNameEn: "Al Qanater Charity",
  ),
  CityModel(
    id: 235,
    governorateId: 12,
    cityNameAr: "الخانكة",
    cityNameEn: "Khanka",
  ),
  CityModel(
    id: 236,
    governorateId: 12,
    cityNameAr: "كفر شكر",
    cityNameEn: "Kafr Shukr",
  ),
  CityModel(
    id: 237,
    governorateId: 12,
    cityNameAr: "طوخ",
    cityNameEn: "Tukh",
  ),
  CityModel(
    id: 238,
    governorateId: 12,
    cityNameAr: "قها",
    cityNameEn: "Qaha",
  ),
  CityModel(
    id: 239,
    governorateId: 12,
    cityNameAr: "العبور",
    cityNameEn: "Obour",
  ),
  CityModel(
    id: 240,
    governorateId: 12,
    cityNameAr: "الخصوص",
    cityNameEn: "Khosous",
  ),
  CityModel(
    id: 241,
    governorateId: 12,
    cityNameAr: "شبين القناطر",
    cityNameEn: "Shibin Al Qanater",
  ),
  CityModel(
    id: 242,
    governorateId: 12,
    cityNameAr: "مسطرد",
    cityNameEn: "Mostorod",
  ),
  CityModel(
    id: 243,
    governorateId: 13,
    cityNameAr: "الخارجة",
    cityNameEn: "El Kharga",
  ),
  CityModel(
    id: 244,
    governorateId: 13,
    cityNameAr: "باريس",
    cityNameEn: "Paris",
  ),
  CityModel(
    id: 245,
    governorateId: 13,
    cityNameAr: "موط",
    cityNameEn: "Mout",
  ),
  CityModel(
    id: 246,
    governorateId: 13,
    cityNameAr: "الفرافرة",
    cityNameEn: "Farafra",
  ),
  CityModel(
    id: 247,
    governorateId: 13,
    cityNameAr: "بلاط",
    cityNameEn: "Balat",
  ),
  CityModel(
    id: 248,
    governorateId: 13,
    cityNameAr: "الداخلة",
    cityNameEn: "Dakhla",
  ),
  CityModel(
    id: 249,
    governorateId: 14,
    cityNameAr: "السويس",
    cityNameEn: "Suez",
  ),
  CityModel(
    id: 250,
    governorateId: 14,
    cityNameAr: "الجناين",
    cityNameEn: "Alganayen",
  ),
  CityModel(
    id: 251,
    governorateId: 14,
    cityNameAr: "عتاقة",
    cityNameEn: "Ataqah",
  ),
  CityModel(
    id: 252,
    governorateId: 14,
    cityNameAr: "العين السخنة",
    cityNameEn: "Ain Sokhna",
  ),
  CityModel(
    id: 253,
    governorateId: 14,
    cityNameAr: "فيصل",
    cityNameEn: "Faysal",
  ),
  CityModel(
    id: 254,
    governorateId: 15,
    cityNameAr: "أسوان",
    cityNameEn: "Aswan",
  ),
  CityModel(
    id: 255,
    governorateId: 15,
    cityNameAr: "أسوان الجديدة",
    cityNameEn: "Aswan El Gedida",
  ),
  CityModel(
    id: 256,
    governorateId: 15,
    cityNameAr: "دراو",
    cityNameEn: "Drau",
  ),
  CityModel(
    id: 257,
    governorateId: 15,
    cityNameAr: "كوم أمبو",
    cityNameEn: "Kom Ombo",
  ),
  CityModel(
    id: 258,
    governorateId: 15,
    cityNameAr: "نصر النوبة",
    cityNameEn: "Nasr Al Nuba",
  ),
  CityModel(
    id: 259,
    governorateId: 15,
    cityNameAr: "كلابشة",
    cityNameEn: "Kalabsha",
  ),
  CityModel(
    id: 260,
    governorateId: 15,
    cityNameAr: "إدفو",
    cityNameEn: "Edfu",
  ),
  CityModel(
    id: 261,
    governorateId: 15,
    cityNameAr: "الرديسية",
    cityNameEn: "Al-Radisiyah",
  ),
  CityModel(
    id: 262,
    governorateId: 15,
    cityNameAr: "البصيلية",
    cityNameEn: "Al Basilia",
  ),
  CityModel(
    id: 263,
    governorateId: 15,
    cityNameAr: "السباعية",
    cityNameEn: "Al Sibaeia",
  ),
  CityModel(
    id: 264,
    governorateId: 15,
    cityNameAr: "ابوسمبل السياحية",
    cityNameEn: "Abo Simbl Al Siyahia",
  ),
  CityModel(
    id: 265,
    governorateId: 15,
    cityNameAr: "مرسى علم",
    cityNameEn: "Marsa Alam",
  ),
  CityModel(
    id: 266,
    governorateId: 16,
    cityNameAr: "أسيوط",
    cityNameEn: "Assiut",
  ),
  CityModel(
    id: 267,
    governorateId: 16,
    cityNameAr: "أسيوط الجديدة",
    cityNameEn: "Assiut El Gedida",
  ),
  CityModel(
    id: 268,
    governorateId: 16,
    cityNameAr: "ديروط",
    cityNameEn: "Dayrout",
  ),
  CityModel(
    id: 269,
    governorateId: 16,
    cityNameAr: "منفلوط",
    cityNameEn: "Manfalut",
  ),
  CityModel(
    id: 270,
    governorateId: 16,
    cityNameAr: "القوصية",
    cityNameEn: "Qusiya",
  ),
  CityModel(
    id: 271,
    governorateId: 16,
    cityNameAr: "أبنوب",
    cityNameEn: "Abnoub",
  ),
  CityModel(
    id: 272,
    governorateId: 16,
    cityNameAr: "أبو تيج",
    cityNameEn: "Abu Tig",
  ),
  CityModel(
    id: 273,
    governorateId: 16,
    cityNameAr: "الغنايم",
    cityNameEn: "El Ghanaim",
  ),
  CityModel(
    id: 274,
    governorateId: 16,
    cityNameAr: "ساحل سليم",
    cityNameEn: "Sahel Selim",
  ),
  CityModel(
    id: 275,
    governorateId: 16,
    cityNameAr: "البداري",
    cityNameEn: "El Badari",
  ),
  CityModel(
    id: 276,
    governorateId: 16,
    cityNameAr: "صدفا",
    cityNameEn: "Sidfa",
  ),
  CityModel(
    id: 277,
    governorateId: 17,
    cityNameAr: "بني سويف",
    cityNameEn: "Bani Sweif",
  ),
  CityModel(
    id: 278,
    governorateId: 17,
    cityNameAr: "بني سويف الجديدة",
    cityNameEn: "Beni Suef El Gedida",
  ),
  CityModel(
    id: 279,
    governorateId: 17,
    cityNameAr: "الواسطى",
    cityNameEn: "Al Wasta",
  ),
  CityModel(
    id: 280,
    governorateId: 17,
    cityNameAr: "ناصر",
    cityNameEn: "Naser",
  ),
  CityModel(
    id: 281,
    governorateId: 17,
    cityNameAr: "إهناسيا",
    cityNameEn: "Ehnasia",
  ),
  CityModel(
    id: 282,
    governorateId: 17,
    cityNameAr: "ببا",
    cityNameEn: "beba",
  ),
  CityModel(
    id: 283,
    governorateId: 17,
    cityNameAr: "الفشن",
    cityNameEn: "Fashn",
  ),
  CityModel(
    id: 284,
    governorateId: 17,
    cityNameAr: "سمسطا",
    cityNameEn: "Somasta",
  ),
  CityModel(
    id: 285,
    governorateId: 17,
    cityNameAr: "الاباصيرى",
    cityNameEn: "Alabbaseri",
  ),
  CityModel(
    id: 286,
    governorateId: 17,
    cityNameAr: "مقبل",
    cityNameEn: "Mokbel",
  ),
  CityModel(
    id: 287,
    governorateId: 18,
    cityNameAr: "بورسعيد",
    cityNameEn: "PorSaid",
  ),
  CityModel(
    id: 288,
    governorateId: 18,
    cityNameAr: "بورفؤاد",
    cityNameEn: "Port Fouad",
  ),
  CityModel(
    id: 289,
    governorateId: 18,
    cityNameAr: "العرب",
    cityNameEn: "Alarab",
  ),
  CityModel(
    id: 290,
    governorateId: 18,
    cityNameAr: "حى الزهور",
    cityNameEn: "Zohour",
  ),
  CityModel(
    id: 291,
    governorateId: 18,
    cityNameAr: "حى الشرق",
    cityNameEn: "Alsharq",
  ),
  CityModel(
    id: 292,
    governorateId: 18,
    cityNameAr: "حى الضواحى",
    cityNameEn: "Aldawahi",
  ),
  CityModel(
    id: 293,
    governorateId: 18,
    cityNameAr: "حى المناخ",
    cityNameEn: "Almanakh",
  ),
  CityModel(
    id: 294,
    governorateId: 18,
    cityNameAr: "حى مبارك",
    cityNameEn: "Mubarak",
  ),
  CityModel(
    id: 295,
    governorateId: 19,
    cityNameAr: "دمياط",
    cityNameEn: "Damietta",
  ),
  CityModel(
    id: 296,
    governorateId: 19,
    cityNameAr: "دمياط الجديدة",
    cityNameEn: "New Damietta",
  ),
  CityModel(
    id: 297,
    governorateId: 19,
    cityNameAr: "رأس البر",
    cityNameEn: "Ras El Bar",
  ),
  CityModel(
    id: 298,
    governorateId: 19,
    cityNameAr: "فارسكور",
    cityNameEn: "Faraskour",
  ),
  CityModel(
    id: 299,
    governorateId: 19,
    cityNameAr: "الزرقا",
    cityNameEn: "Zarqa",
  ),
  CityModel(
    id: 300,
    governorateId: 19,
    cityNameAr: "السرو",
    cityNameEn: "alsaru",
  ),
  CityModel(
    id: 301,
    governorateId: 19,
    cityNameAr: "الروضة",
    cityNameEn: "alruwda",
  ),
  CityModel(
    id: 302,
    governorateId: 19,
    cityNameAr: "كفر البطيخ",
    cityNameEn: "Kafr El-Batikh",
  ),
  CityModel(
    id: 303,
    governorateId: 19,
    cityNameAr: "عزبة البرج",
    cityNameEn: "Azbet Al Burg",
  ),
  CityModel(
    id: 304,
    governorateId: 19,
    cityNameAr: "ميت أبو غالب",
    cityNameEn: "Meet Abou Ghalib",
  ),
  CityModel(
    id: 305,
    governorateId: 19,
    cityNameAr: "كفر سعد",
    cityNameEn: "Kafr Saad",
  ),
  CityModel(
    id: 306,
    governorateId: 20,
    cityNameAr: "الزقازيق",
    cityNameEn: "Zagazig",
  ),
  CityModel(
    id: 307,
    governorateId: 20,
    cityNameAr: "العاشر من رمضان",
    cityNameEn: "Al Ashr Men Ramadan",
  ),
  CityModel(
    id: 308,
    governorateId: 20,
    cityNameAr: "منيا القمح",
    cityNameEn: "Minya Al Qamh",
  ),
  CityModel(
    id: 309,
    governorateId: 20,
    cityNameAr: "بلبيس",
    cityNameEn: "Belbeis",
  ),
  CityModel(
    id: 310,
    governorateId: 20,
    cityNameAr: "مشتول السوق",
    cityNameEn: "Mashtoul El Souq",
  ),
  CityModel(
    id: 311,
    governorateId: 20,
    cityNameAr: "القنايات",
    cityNameEn: "Qenaiat",
  ),
  CityModel(
    id: 312,
    governorateId: 20,
    cityNameAr: "أبو حماد",
    cityNameEn: "Abu Hammad",
  ),
  CityModel(
    id: 313,
    governorateId: 20,
    cityNameAr: "القرين",
    cityNameEn: "El Qurain",
  ),
  CityModel(
    id: 314,
    governorateId: 20,
    cityNameAr: "ههيا",
    cityNameEn: "Hehia",
  ),
  CityModel(
    id: 315,
    governorateId: 20,
    cityNameAr: "أبو كبير",
    cityNameEn: "Abu Kabir",
  ),
  CityModel(
    id: 316,
    governorateId: 20,
    cityNameAr: "فاقوس",
    cityNameEn: "Faccus",
  ),
  CityModel(
    id: 317,
    governorateId: 20,
    cityNameAr: "الصالحية الجديدة",
    cityNameEn: "El Salihia El Gedida",
  ),
  CityModel(
    id: 318,
    governorateId: 20,
    cityNameAr: "الإبراهيمية",
    cityNameEn: "Al Ibrahimiyah",
  ),
  CityModel(
    id: 319,
    governorateId: 20,
    cityNameAr: "ديرب نجم",
    cityNameEn: "Deirb Negm",
  ),
  CityModel(
    id: 320,
    governorateId: 20,
    cityNameAr: "كفر صقر",
    cityNameEn: "Kafr Saqr",
  ),
  CityModel(
    id: 321,
    governorateId: 20,
    cityNameAr: "أولاد صقر",
    cityNameEn: "Awlad Saqr",
  ),
  CityModel(
    id: 322,
    governorateId: 20,
    cityNameAr: "الحسينية",
    cityNameEn: "Husseiniya",
  ),
  CityModel(
    id: 323,
    governorateId: 20,
    cityNameAr: "صان الحجر القبلية",
    cityNameEn: "san alhajar alqablia",
  ),
  CityModel(
    id: 324,
    governorateId: 20,
    cityNameAr: "منشأة أبو عمر",
    cityNameEn: "Manshayat Abu Omar",
  ),
  CityModel(
    id: 325,
    governorateId: 21,
    cityNameAr: "الطور",
    cityNameEn: "Al Toor",
  ),
  CityModel(
    id: 326,
    governorateId: 21,
    cityNameAr: "شرم الشيخ",
    cityNameEn: "Sharm El-Shaikh",
  ),
  CityModel(
    id: 327,
    governorateId: 21,
    cityNameAr: "دهب",
    cityNameEn: "Dahab",
  ),
  CityModel(
    id: 328,
    governorateId: 21,
    cityNameAr: "نويبع",
    cityNameEn: "Nuweiba",
  ),
  CityModel(
    id: 329,
    governorateId: 21,
    cityNameAr: "طابا",
    cityNameEn: "Taba",
  ),
  CityModel(
    id: 330,
    governorateId: 21,
    cityNameAr: "سانت كاترين",
    cityNameEn: "Saint Catherine",
  ),
  CityModel(
    id: 331,
    governorateId: 21,
    cityNameAr: "أبو رديس",
    cityNameEn: "Abu Redis",
  ),
  CityModel(
    id: 332,
    governorateId: 21,
    cityNameAr: "أبو زنيمة",
    cityNameEn: "Abu Zenaima",
  ),
  CityModel(
    id: 333,
    governorateId: 21,
    cityNameAr: "رأس سدر",
    cityNameEn: "Ras Sidr",
  ),
  CityModel(
    id: 334,
    governorateId: 22,
    cityNameAr: "كفر الشيخ",
    cityNameEn: "Kafr El Sheikh",
  ),
  CityModel(
    id: 335,
    governorateId: 22,
    cityNameAr: "وسط البلد كفر الشيخ",
    cityNameEn: "Kafr El Sheikh Downtown",
  ),
  CityModel(
    id: 336,
    governorateId: 22,
    cityNameAr: "دسوق",
    cityNameEn: "Desouq",
  ),
  CityModel(
    id: 337,
    governorateId: 22,
    cityNameAr: "فوه",
    cityNameEn: "Fooh",
  ),
  CityModel(
    id: 338,
    governorateId: 22,
    cityNameAr: "مطوبس",
    cityNameEn: "Metobas",
  ),
  CityModel(
    id: 339,
    governorateId: 22,
    cityNameAr: "برج البرلس",
    cityNameEn: "Burg Al Burullus",
  ),
  CityModel(
    id: 340,
    governorateId: 22,
    cityNameAr: "بلطيم",
    cityNameEn: "Baltim",
  ),
  CityModel(
    id: 341,
    governorateId: 22,
    cityNameAr: "مصيف بلطيم",
    cityNameEn: "Masief Baltim",
  ),
  CityModel(
    id: 342,
    governorateId: 22,
    cityNameAr: "الحامول",
    cityNameEn: "Hamol",
  ),
  CityModel(
    id: 343,
    governorateId: 22,
    cityNameAr: "بيلا",
    cityNameEn: "Bella",
  ),
  CityModel(
    id: 344,
    governorateId: 22,
    cityNameAr: "الرياض",
    cityNameEn: "Riyadh",
  ),
  CityModel(
    id: 345,
    governorateId: 22,
    cityNameAr: "سيدي سالم",
    cityNameEn: "Sidi Salm",
  ),
  CityModel(
    id: 346,
    governorateId: 22,
    cityNameAr: "قلين",
    cityNameEn: "Qellen",
  ),
  CityModel(
    id: 347,
    governorateId: 22,
    cityNameAr: "سيدي غازي",
    cityNameEn: "Sidi Ghazi",
  ),
  CityModel(
    id: 348,
    governorateId: 23,
    cityNameAr: "مرسى مطروح",
    cityNameEn: "Marsa Matrouh",
  ),
  CityModel(
    id: 349,
    governorateId: 23,
    cityNameAr: "الحمام",
    cityNameEn: "El Hamam",
  ),
  CityModel(
    id: 350,
    governorateId: 23,
    cityNameAr: "العلمين",
    cityNameEn: "Alamein",
  ),
  CityModel(
    id: 351,
    governorateId: 23,
    cityNameAr: "الضبعة",
    cityNameEn: "Dabaa",
  ),
  CityModel(
    id: 352,
    governorateId: 23,
    cityNameAr: "النجيلة",
    cityNameEn: "Al-Nagila",
  ),
  CityModel(
    id: 353,
    governorateId: 23,
    cityNameAr: "سيدي براني",
    cityNameEn: "Sidi Brani",
  ),
  CityModel(
    id: 354,
    governorateId: 23,
    cityNameAr: "السلوم",
    cityNameEn: "Salloum",
  ),
  CityModel(
    id: 355,
    governorateId: 23,
    cityNameAr: "سيوة",
    cityNameEn: "Siwa",
  ),
  CityModel(
    id: 356,
    governorateId: 23,
    cityNameAr: "مارينا",
    cityNameEn: "Marina",
  ),
  CityModel(
    id: 357,
    governorateId: 23,
    cityNameAr: "الساحل الشمالى",
    cityNameEn: "North Coast",
  ),
  CityModel(
    id: 358,
    governorateId: 24,
    cityNameAr: "الأقصر",
    cityNameEn: "Luxor",
  ),
  CityModel(
    id: 359,
    governorateId: 24,
    cityNameAr: "الأقصر الجديدة",
    cityNameEn: "New Luxor",
  ),
  CityModel(
    id: 360,
    governorateId: 24,
    cityNameAr: "إسنا",
    cityNameEn: "Esna",
  ),
  CityModel(
    id: 361,
    governorateId: 24,
    cityNameAr: "طيبة الجديدة",
    cityNameEn: "New Tiba",
  ),
  CityModel(
    id: 362,
    governorateId: 24,
    cityNameAr: "الزينية",
    cityNameEn: "Al ziynia",
  ),
  CityModel(
    id: 363,
    governorateId: 24,
    cityNameAr: "البياضية",
    cityNameEn: "Al Bayadieh",
  ),
  CityModel(
    id: 364,
    governorateId: 24,
    cityNameAr: "القرنة",
    cityNameEn: "Al Qarna",
  ),
  CityModel(
    id: 365,
    governorateId: 24,
    cityNameAr: "أرمنت",
    cityNameEn: "Armant",
  ),
  CityModel(
    id: 366,
    governorateId: 24,
    cityNameAr: "الطود",
    cityNameEn: "Al Tud",
  ),
  CityModel(
    id: 367,
    governorateId: 25,
    cityNameAr: "قنا",
    cityNameEn: "Qena",
  ),
  CityModel(
    id: 368,
    governorateId: 25,
    cityNameAr: "قنا الجديدة",
    cityNameEn: "New Qena",
  ),
  CityModel(
    id: 369,
    governorateId: 25,
    cityNameAr: "ابو طشت",
    cityNameEn: "Abu Tesht",
  ),
  CityModel(
    id: 370,
    governorateId: 25,
    cityNameAr: "نجع حمادي",
    cityNameEn: "Nag Hammadi",
  ),
  CityModel(
    id: 371,
    governorateId: 25,
    cityNameAr: "دشنا",
    cityNameEn: "Deshna",
  ),
  CityModel(
    id: 372,
    governorateId: 25,
    cityNameAr: "الوقف",
    cityNameEn: "Alwaqf",
  ),
  CityModel(
    id: 373,
    governorateId: 25,
    cityNameAr: "قفط",
    cityNameEn: "Qaft",
  ),
  CityModel(
    id: 374,
    governorateId: 25,
    cityNameAr: "نقادة",
    cityNameEn: "Naqada",
  ),
  CityModel(
    id: 375,
    governorateId: 25,
    cityNameAr: "فرشوط",
    cityNameEn: "Farshout",
  ),
  CityModel(
    id: 376,
    governorateId: 25,
    cityNameAr: "قوص",
    cityNameEn: "Quos",
  ),
  CityModel(
    id: 377,
    governorateId: 26,
    cityNameAr: "العريش",
    cityNameEn: "Arish",
  ),
  CityModel(
    id: 378,
    governorateId: 26,
    cityNameAr: "الشيخ زويد",
    cityNameEn: "Sheikh Zowaid",
  ),
  CityModel(
    id: 379,
    governorateId: 26,
    cityNameAr: "نخل",
    cityNameEn: "Nakhl",
  ),
  CityModel(
    id: 380,
    governorateId: 26,
    cityNameAr: "رفح",
    cityNameEn: "Rafah",
  ),
  CityModel(
    id: 381,
    governorateId: 26,
    cityNameAr: "بئر العبد",
    cityNameEn: "Bir al-Abed",
  ),
  CityModel(
    id: 382,
    governorateId: 26,
    cityNameAr: "الحسنة",
    cityNameEn: "Al Hasana",
  ),
  CityModel(
    id: 383,
    governorateId: 27,
    cityNameAr: "سوهاج",
    cityNameEn: "Sohag",
  ),
  CityModel(
    id: 384,
    governorateId: 27,
    cityNameAr: "سوهاج الجديدة",
    cityNameEn: "Sohag El Gedida",
  ),
  CityModel(
    id: 385,
    governorateId: 27,
    cityNameAr: "أخميم",
    cityNameEn: "Akhmeem",
  ),
  CityModel(
    id: 386,
    governorateId: 27,
    cityNameAr: "أخميم الجديدة",
    cityNameEn: "Akhmim El Gedida",
  ),
  CityModel(
    id: 387,
    governorateId: 27,
    cityNameAr: "البلينا",
    cityNameEn: "Albalina",
  ),
  CityModel(
    id: 388,
    governorateId: 27,
    cityNameAr: "المراغة",
    cityNameEn: "El Maragha",
  ),
  CityModel(
    id: 389,
    governorateId: 27,
    cityNameAr: "المنشأة",
    cityNameEn: "almunsha'a",
  ),
  CityModel(
    id: 390,
    governorateId: 27,
    cityNameAr: "دار السلام",
    cityNameEn: "Dar AISalaam",
  ),
  CityModel(
    id: 391,
    governorateId: 27,
    cityNameAr: "جرجا",
    cityNameEn: "Gerga",
  ),
  CityModel(
    id: 392,
    governorateId: 27,
    cityNameAr: "جهينة الغربية",
    cityNameEn: "Jahina Al Gharbia",
  ),
  CityModel(
    id: 393,
    governorateId: 27,
    cityNameAr: "ساقلته",
    cityNameEn: "Saqilatuh",
  ),
  CityModel(
    id: 394,
    governorateId: 27,
    cityNameAr: "طما",
    cityNameEn: "Tama",
  ),
  CityModel(
    id: 395,
    governorateId: 27,
    cityNameAr: "طهطا",
    cityNameEn: "Tahta",
  ),
  CityModel(
    id: 396,
    governorateId: 27,
    cityNameAr: "الكوثر",
    cityNameEn: "Alkawthar",
  ),
];
